#!/usr/bin/env lua

local home = os.getenv("HOME")
local config_dir = os.getenv("CONFIG_DIR") or (home .. "/.config/sketchybar")

package.path = config_dir .. "/?.lua;" .. config_dir .. "/?/init.lua;" .. package.path
package.cpath = home .. "/.local/share/sketchybar_lua/?.so;" .. package.cpath

require("init")
